# Custom Language File for Launcher Customizer

[ejs.app]
title = "크리스마스 힐링 마을"

[ejs.landing]
mediaGitHubURL = "https://github.com/mchlauncher/moolchoko"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = ""
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/moolchoko"
supportLink = "https://github.com/mchlauncher/moolchoko/issues"

[ejs.welcome]
welcomeHeader = "크리스마스 힐링 마을"
welcomeDescription = ""
welcomeDescCTA = "[계속] 버튼을 눌러 계속 진행하여 주세요."